# Generated by Django 3.2.9 on 2021-12-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="Constant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k", models.IntegerField(default=20)),
            ],
        ),
    ]
