# Generated by Django 3.2.9 on 2021-12-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_elo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="points_1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="points_2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="turns_1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="turns_2",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
