# Generated by Django 5.1 on 2024-09-02 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_rename_player_id_albo_player_and_more"),
    ]

    operations = [migrations.RenameModel("Constant", "Parameters")]
