# Generated by Django 5.1 on 2024-09-02 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_match_season_result_tournament_match_tournament"),
    ]

    operations = [
        # Generated by Django 5.1 on 2024-09-02 23:02
        migrations.RenameModel("Parameters", "Parameter"),
        migrations.RenameModel("Elo", "EloOld"),
    ]
