# Generated by Django 5.1 on 2024-09-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_eloscore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eloold",
            name="player",
        ),
        migrations.RemoveField(
            model_name="eloold",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="game",
            name="player_id_1",
        ),
        migrations.RemoveField(
            model_name="game",
            name="player_id_2",
        ),
        migrations.RemoveField(
            model_name="game",
            name="tournament",
        ),
        migrations.AlterField(
            model_name="result",
            name="num_points",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="result",
            name="num_turns",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="Albo",
        ),
        migrations.DeleteModel(
            name="EloOld",
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="Metadata",
        ),
    ]
