# Generated by Django 3.2.9 on 2021-12-02 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_1', models.IntegerField()),
                ('turns_1', models.IntegerField()),
                ('points_2', models.IntegerField()),
                ('turns_2', models.IntegerField()),
                ('player_id_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_id_1', to=settings.AUTH_USER_MODEL)),
                ('player_id_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_id_2', to=settings.AUTH_USER_MODEL)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.metadata')),
            ],
        ),
    ]
