# Generated by Django 3.2.9 on 2021-12-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_albo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('champ_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('participants', models.CharField(max_length=200)),
                ('tours', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
