# Generated by Django 3.2.9 on 2021-12-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_championship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='participants',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='championship',
            name='tours',
            field=models.CharField(default='', max_length=255),
        ),
    ]
