# Generated by Django 3.2.9 on 2021-12-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211215_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='participants',
            field=models.CharField(default='[]', max_length=200),
        ),
        migrations.AlterField(
            model_name='championship',
            name='tours',
            field=models.CharField(default='[]', max_length=255),
        ),
    ]
